<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <Version>0.1.0.0</Version>
    <PackageProjectUrl>https://github.com/ShoValentine/KupoCombo</PackageProjectUrl>
    <PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>
    <IsPackable>false</IsPackable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="..\Data\Sequences\*.json">
      <Link>Sequences\%(Filename)%(Extension)</Link>
      <TargetPath>Sequences\%(Filename)%(Extension)</TargetPath>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Visible>false</Visible>
    </Content>

    <Content Include="..\Data\Guidance\*.json">
      <Link>Guidance\%(Filename)%(Extension)</Link>
      <TargetPath>Guidance\%(Filename)%(Extension)</TargetPath>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Visible>false</Visible>
    </Content>

    <Content Include="..\Data\Policies\*.json">
      <Link>Policies\%(Filename)%(Extension)</Link>
      <TargetPath>Policies\%(Filename)%(Extension)</TargetPath>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Visible>false</Visible>
    </Content>

    <Content Include="..\Data\Schemas\*.json">
      <Link>Schemas\%(Filename)%(Extension)</Link>
      <TargetPath>Schemas\%(Filename)%(Extension)</TargetPath>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Visible>false</Visible>
    </Content>

    <Content Include="..\Data\kupoicon.png">
      <Link>Assets\kupoicon.png</Link>
      <TargetPath>Assets\kupoicon.png</TargetPath>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Visible>false</Visible>
    </Content>
  </ItemGroup>
</Project>
